version: '3'
services:
# nginx
  nginx:
    container_name: nginx
    build:
      context: ./nginx
    volumes:
      - ${WEB_ROOT}:/var/www/html
      - ../data/nginx/logs/:/var/log/nginx/
    ports:
      - "${NGINX_HTTP_PORT}:80"
      - "${NGINX_HTTPS_PORT}:443"
    environment:
      - TZ=Asia/Shanghai
      - LANG=en_US.UTF-8
    depends_on:
      - php
      - supervisor
    restart: always

# php
  php:
    container_name: php
    build:
      context: ./php
    volumes:
      - ${WEB_ROOT}:/var/www/html
      - ../data/php/logs:/var/log/php/
    expose:
      - 9000
    depends_on:
      - mysql
      - redis
    restart: always

# supervisor
  supervisor:
    container_name: supervisor
    build:
      context: ./
      dockerfile: supervisor/Dockerfile
    volumes:
      - ${WEB_ROOT}:/var/www/html
      - ../data/supervisor/logs:/var/log/supervisor/
    expose:
      - 9000
      - 11118
      - 9001
    ports:
      - "11118:11118"
      - "${HORIZON_PORT}:9001"
    depends_on:
      - php
      - mysql
      - redis
    restart: always

# mysql
  mysql:
    container_name: mysql
    build:
      context: ./
      dockerfile: mysql/Dockerfile
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - ../data/mysql:/var/lib/mysql
    expose:
      - 3306
    environment:
      - MYSQL_ROOT_PASSWORD="${MYSQL_PASSWORD}"
      - MYSQL_DATABASE=ds
    restart: always
    command:
      --default-authentication-plugin=mysql_native_password

# redis
  redis:
    container_name: redis
    build:
      context: ./
      dockerfile: redis/Dockerfile
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - ../data/redis:/data
      - ../data/redis/logs:/var/log/redis
    environment:
      - TZ=Asia/Shanghai
    command: redis-server /etc/redis/redis.conf --requirepass ${REDIS_PASSWORD} --appendonly yes --logfile /var/log/redis/redis.log
    restart: always

# phpmyadmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    ports:
      - "${PHPMYADMIN_PORT}:80"
    environment:
      - PMA_HOST=mysql
    depends_on:
      - mysql
    restart: always

# phpredisadmin
  phpredisadmin:
    image: erikdubbelboer/phpredisadmin:latest
    container_name: phpredisadmin
    ports:
      - "${PHPREDISADMIN_PORT}:80"
    environment:
      - TZ=Asia/Shanghai
      - REDIS_1_HOST=redis
      - REDIS_1_PORT=6379
      - REDIS_1_AUTH=${REDIS_PASSWORD}
      - ADMIN_USER=root
      - ADMIN_PASS=${REDIS_PASSWORD}
    depends_on:
      - redis
    restart: always

networks:
  default:
    external:
      name: ${NETWORK_PORT_LIST}
