version: '3'
services:
# nginx
  nginx:
    image: nginx:1.21.6
    container_name: nginx
    volumes:
      - ${WEB_ROOT}:/var/www/html
    ports:
      - "${NGINX_HTTP_PORT}:80"
      - "${NGINX_HTTPS_PORT}:443"
    environment:
      - TZ=Asia/Shanghai
      - LANG=en_US.UTF-8
    depends_on:
      - php
    restart: always

# php
  php:
    image: php:8.1.0RC5-fpm-buster
    container_name: php
    build:
      context: ./php
    volumes:
      - ${WEB_ROOT}:/var/www/html
    expose:
      - "9000"
    depends_on:
      - mysql
      - redis
    restart: always

# mysql
  mysql:
    image: amd64/mysql:8.0.29-oracle
    container_name: mysql
    build:
      context: ./mysql
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - ../data/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=test
      - MYSQL_USER=test
      - MYSQL_PASSWORD=test
    restart: always
    command:
      --default-authentication-plugin=mysql_native_password

  # redis
  redis:
    image: redis:6.2.6
    container_name: redis
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - ../data/redis:/data
    environment:
      - TZ=Asia/Shanghai
    command: redis-server --requirepass root --appendonly yes
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
    restart: always

# phpmyadmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    ports:
      - "${PHPMYADMIN_PORT}:80"
    environment:
      - PMA_ARBITRARY=1
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_ROOT_PASSWORD=root
      - PMA_HOST=mysql
    depends_on:
      - mysql
    restart: always

# phpredisadmin
  phpredisadmin:
    image: erikdubbelboer/phpredisadmin:latest
    container_name: phpredisadmin
    ports:
      - "${PHPREDISADMIN}:80"
    environment:
      - TZ=Asia/Shanghai
      - REDIS_1_HOST=redis
      - REDIS_1_PORT=6379
      - REDIS_1_AUTH=root
      - ADMIN_USER=root
      - ADMIN_PASS=root
    depends_on:
      - redis
    restart: always

networks:
  default:
    external:
      name: ${NETWORK_PORT_LIST}