version: '3'
services:
# nginx
  nginx:
    container_name: nginx
    build:
      context: ./nginx
    volumes:
      - ${WEB_ROOT}:/var/www/html
      - ../data/nginx/logs/:/var/log/nginx/
    ports:
      - "${NGINX_HTTP_PORT}:80"
      - "${NGINX_HTTPS_PORT}:443"
    environment:
      - TZ=Asia/Shanghai
      - LANG=en_US.UTF-8
    depends_on:
      - php-fpm
    restart: always

# php
  php-fpm:
    container_name: php
    build:
      context: ./php
    volumes:
      - ${WEB_ROOT}:/var/www/html
      - ../data/php/logs:/var/log/php/
    expose:
      - 9000
    depends_on:
      - mysql
      - redis
    restart: always

# supervisor
  supervisor:
    container_name: supervisor
    build:
      context: ./supervisor
    volumes:
      - ${WEB_ROOT}:/var/www/html
      - ../data/supervisor/logs:/var/log/supervisor/
    depends_on:
      - php-fpm
      - mysql
      - redis
    restart: always

# mysql
  mysql:
    container_name: mysql
    build:
      context: ./mysql
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - ../data/mysql:/var/lib/mysql
    expose:
      - 3306
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=ds
    restart: always
    command:
      --default-authentication-plugin=mysql_native_password

# redis
  redis:
    image: redis:6.2.6
    container_name: redis
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - ../data/redis:/data
      - ../data/redis/logs:/var/log/redis/redis.log
    environment:
      - TZ=Asia/Shanghai
    command: redis-server --requirepass root --appendonly yes
    restart: always

# phpmyadmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    ports:
      - "${PHPMYADMIN_PORT}:80"
    environment:
      - PMA_HOST=mysql
    depends_on:
      - mysql
    restart: always

# phpredisadmin
  phpredisadmin:
    image: erikdubbelboer/phpredisadmin:latest
    container_name: phpredisadmin
    ports:
      - "${PHPREDISADMIN_PORT}:80"
    environment:
      - TZ=Asia/Shanghai
      - REDIS_1_HOST=redis
      - REDIS_1_PORT=6379
      - REDIS_1_AUTH=root
      - ADMIN_USER=root
      - ADMIN_PASS=root
    depends_on:
      - redis
    restart: always

networks:
  default:
    external:
      name: ${NETWORK_PORT_LIST}
